#!/bin/bash

rm -f restart_photo

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
#./star inlist_relax   | tee log.relax
./star inlist_prezams | tee log.prezams
./star inlist_solar   | tee log.solar
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
